---
- hosts: all
  gather_facts: no
  tasks:
    - name: Add ppa:nginx/stable repo
      apt_repository: repo='ppa:nginx/stable'

    - name: Install nginx, curl and tree
      apt: pkg={{ item }} state=present
      with_items:
        - nginx
        - curl
        - tree

    - name: Configure website
      copy: src=website.conf dest=/etc/nginx/sites-enabled/website.conf
      notify: nginx restart

    - name: Ensure nginx is running
      command: service nginx start

    - name: Create website root
      file: path=/srv/website state=directory

    - name: Add a nice page
      copy: content="Hello world" dest=/srv/website/hello.txt

  handlers:
    - name: nginx restart
      command: service nginx restart
